version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - /srv/media-stack/jellyfin:/config
      - /srv/media/movies:/movies
      - jellyfin_cache:/cache
    environment:
      - XDG_CACHE_HOME=/cache
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /srv/media-stack/radarr:/config
      - /srv/media/downloads:/downloads
      - /srv/media/movies:/movies
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8080
    volumes:
      - /srv/media-stack/qbittorrent:/config
      - /srv/media/downloads:/downloads
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /srv/media-stack/jackett:/config
      - /srv/media/downloads:/downloads
    restart: unless-stopped

volumes:
  jellyfin_cache:
